apiVersion: apps/v1beta2
kind: Deployment
metadata:
  labels:
    app: zssgeblkbk-www
    volkn/cd-name_github_ybrin_zssgeblkbk: master.0
  name: zssgeblkbk-www
  namespace: dev
spec:
  replicas: 1
  selector:
    matchLabels:
      app: zssgeblkbk-www
  strategy:
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 0
    type: RollingUpdate
  template:
    metadata:
      labels:
        app: zssgeblkbk-www
    spec:
      containers:
      - image: ""
        imagePullPolicy: Always
        name: zssgeblkbk-www
        resources: {}
        securityContext:
          allowPrivilegeEscalation: false
          capabilities: {}
          privileged: false
          readOnlyRootFilesystem: false
          runAsNonRoot: false
        stdin: true
        terminationMessagePath: /dev/termination-log
        terminationMessagePolicy: File
        tty: true
      dnsPolicy: ClusterFirst
      restartPolicy: Always
      schedulerName: default-scheduler
      securityContext: {}
      terminationGracePeriodSeconds: 30
