apiVersion: v1
kind: Service
metadata:
  name: zssgeblkbk-www-service
  namespace: dev
spec:
  type: ClusterIP
  selector:
    app: zssgeblkbk-www
  ports:
    - port: 80
      targetPort: 80
      name: http
